// <auto-generated />
using System;
using CBSMonitoring.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CBSMonitoring.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230814125321_ChangeToForm")]
    partial class ChangeToForm
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CBSMonitoring.Model.Organization", b =>
                {
                    b.Property<int>("OrganizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrganizationId"));

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("OrganizationId");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("CBSMonitoring.Models.FileModel", b =>
                {
                    b.Property<int>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FileId"));

                    b.Property<string>("BasePath")
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DocDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocNumber")
                        .HasColumnType("text");

                    b.Property<string>("Extension")
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<int?>("Form1_1MonitoringId")
                        .HasColumnType("integer");

                    b.Property<int?>("Form2_1MonitoringId")
                        .HasColumnType("integer");

                    b.Property<int?>("Form2_2MonitoringId")
                        .HasColumnType("integer");

                    b.Property<int?>("Form2_3MonitoringId")
                        .HasColumnType("integer");

                    b.Property<int?>("Form2_4MonitoringId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("SystemPath")
                        .HasColumnType("text");

                    b.HasKey("FileId");

                    b.HasIndex("Form1_1MonitoringId");

                    b.HasIndex("Form2_1MonitoringId");

                    b.HasIndex("Form2_2MonitoringId");

                    b.HasIndex("Form2_3MonitoringId");

                    b.HasIndex("Form2_4MonitoringId");

                    b.ToTable("FileModels");
                });

            modelBuilder.Entity("CBSMonitoring.Models.FormItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemId"));

                    b.Property<int>("FormId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemLabel")
                        .HasColumnType("text");

                    b.Property<string>("ItemName")
                        .HasColumnType("text");

                    b.Property<string>("ItemType")
                        .HasColumnType("text");

                    b.Property<int?>("LinkedItemId")
                        .HasColumnType("integer");

                    b.Property<int?>("ListIndex")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string[]>("SelectOptions")
                        .HasColumnType("text[]");

                    b.HasKey("ItemId");

                    b.HasIndex("FormId");

                    b.ToTable("FormItems");
                });

            modelBuilder.Entity("CBSMonitoring.Models.MonitoringForm", b =>
                {
                    b.Property<int>("FormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FormId"));

                    b.Property<string>("FormNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("FormId");

                    b.ToTable("MonitoringForms");
                });

            modelBuilder.Entity("CBSMonitoring.Models.OrgMonitoring", b =>
                {
                    b.Property<int>("MonitoringId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MonitoringId"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<int>("QuaterIndex")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("MonitoringId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("OrgMonitorings");

                    b.HasDiscriminator<string>("Discriminator").HasValue("OrgMonitoring");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CBSMonitoring.Models.QualificationImprovedEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CertificateFileId")
                        .HasColumnType("integer");

                    b.Property<string>("CourseConductedOrgName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EducationPeriod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Form2_8MonitoringId")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CertificateFileId");

                    b.HasIndex("Form2_8MonitoringId");

                    b.ToTable("QIEmployees");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CBSMonitoring.Models.Form1_1", b =>
                {
                    b.HasBaseType("CBSMonitoring.Models.OrgMonitoring");

                    b.Property<bool?>("AgreedWithAuthBody")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasISPRevised")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasPolicy")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsAuditConducted")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsReviewedByCBS")
                        .HasColumnType("boolean");

                    b.Property<int?>("NumberOfEmployees")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfRevision")
                        .HasColumnType("integer");

                    b.Property<float?>("PercentageOfEmpFamiliarWithPolicy")
                        .HasColumnType("real");

                    b.Property<int?>("YearOfRevisions")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Form1_1");
                });

            modelBuilder.Entity("CBSMonitoring.Models.Form1_2", b =>
                {
                    b.HasBaseType("CBSMonitoring.Models.OrgMonitoring");

                    b.Property<string>("ListOfRegDocs")
                        .HasColumnType("text");

                    b.Property<int?>("NumberOfRegDocs")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Form1_2");
                });

            modelBuilder.Entity("CBSMonitoring.Models.Form1_3", b =>
                {
                    b.HasBaseType("CBSMonitoring.Models.OrgMonitoring");

                    b.Property<string>("ListOfRegJournal")
                        .HasColumnType("text");

                    b.Property<int?>("NumberOfRegJournal")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Form1_3");
                });

            modelBuilder.Entity("CBSMonitoring.Models.Form1_4", b =>
                {
                    b.HasBaseType("CBSMonitoring.Models.OrgMonitoring");

                    b.Property<DateTime?>("ComissionDocDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ComissionDocNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ConfidentialDocDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConfidentialDocNumber")
                        .HasColumnType("text");

                    b.Property<bool?>("IsComissionPresent")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsListAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsListCommToEmps")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsListOfOfficialAvailable")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("OfficialsDocDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OfficialsDocNumber")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Form1_4");
                });

            modelBuilder.Entity("CBSMonitoring.Models.Form1_5", b =>
                {
                    b.HasBaseType("CBSMonitoring.Models.OrgMonitoring");

                    b.Property<bool?>("IsAgreementsAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsRelevantClausesAvailable")
                        .HasColumnType("boolean");

                    b.Property<int?>("NumberOfEmplFamWithAgreements")
                        .HasColumnType("integer");

                    b.Property<float?>("PercentageOfEmpFamWithAgreements")
                        .HasColumnType("real");

                    b.HasDiscriminator().HasValue("Form1_5");
                });

            modelBuilder.Entity("CBSMonitoring.Models.Form2_1", b =>
                {
                    b.HasBaseType("CBSMonitoring.Models.OrgMonitoring");

                    b.Property<bool?>("IsActionPlanAgreedToEnsIC")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsActionPlanAvailableToEnsIC")
                        .HasColumnType("boolean");

                    b.Property<string>("ReasonForAbsenceOfAgreement")
                        .HasColumnType("text");

                    b.Property<string>("ReasonForAbsenceOfPlan")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Form2_1");
                });

            modelBuilder.Entity("CBSMonitoring.Models.Form2_10", b =>
                {
                    b.HasBaseType("CBSMonitoring.Models.OrgMonitoring");

                    b.Property<DateTime?>("AuditConcDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AuditPeriod")
                        .HasColumnType("text");

                    b.Property<string>("AuditedObjectsNames")
                        .HasColumnType("text");

                    b.Property<bool?>("IsObjectsAudited")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsShortcomingDetected")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsShortcomingsOfObjecttEliminated")
                        .HasColumnType("boolean");

                    b.Property<string>("NumberOfAuditConc")
                        .HasColumnType("text");

                    b.Property<string>("OrgNameMadeAudit")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Form2_10");
                });

            modelBuilder.Entity("CBSMonitoring.Models.Form2_11", b =>
                {
                    b.HasBaseType("CBSMonitoring.Models.OrgMonitoring");

                    b.Property<bool?>("AvailabilityOfSecAlarmsInCentre")
                        .HasColumnType("boolean");

                    b.Property<bool?>("AvailabilityOfVideoCamInServerRoom")
                        .HasColumnType("boolean");

                    b.Property<bool?>("AvailablityOfFalseFloorAndCeiling")
                        .HasColumnType("boolean");

                    b.Property<bool?>("AvailablityOfLogsForServerRoomEntrance")
                        .HasColumnType("boolean");

                    b.Property<bool?>("AvailablityOfTempSensors")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsACSAvialble")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsAntiFireEquipAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsCheckInOutLogAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsCoolingSystemAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsDataCentreAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsEntranceSecurityAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsPlanForPreventiveMaintAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsServerRoomAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsSurveillanceCamerasAvailable")
                        .HasColumnType("boolean");

                    b.Property<int?>("NumberOfDataCentre")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfObjInACS")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfObjWithSecurity")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfPointsInLog")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfRoomsMonitoredByAlarms")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfSRandDCWithMetalDoor")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfSRandDCWithWithSystemControl")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfServerRoom")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfServersWithSealedOuterCases")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfStructObjsWithCams")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfTerritObjsWithAlarms")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfVideoCamsInCentre")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfVideoCamsInTerritorialObjs")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfWorkStWithSealedOuterCases")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Form2_11");
                });

            modelBuilder.Entity("CBSMonitoring.Models.Form2_12", b =>
                {
                    b.HasBaseType("CBSMonitoring.Models.OrgMonitoring");

                    b.Property<bool?>("IsAnyIncidentResoluted")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsDepISAndHeadNotified")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsIncidentsInvestigated")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsLogsForIncidentsAvailable")
                        .HasColumnType("boolean");

                    b.Property<int?>("NumOFIncidentsResoluted")
                        .HasColumnType("integer");

                    b.Property<int?>("NumOfIncidentsInStructOrg")
                        .HasColumnType("integer");

                    b.Property<int?>("NumOfIncidentsInSubObjects")
                        .HasColumnType("integer");

                    b.Property<int?>("NumOfIncidentsInvestigated")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfIncidents")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfObjWithIncidentLog")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Form2_12");
                });

            modelBuilder.Entity("CBSMonitoring.Models.Form2_13", b =>
                {
                    b.HasBaseType("CBSMonitoring.Models.OrgMonitoring");

                    b.Property<string>("BackupFrequency")
                        .HasColumnType("text");

                    b.Property<bool?>("IsApprovedScheduleForBackupAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsBackupMeasuresProvided")
                        .HasColumnType("boolean");

                    b.Property<int?>("NumOfConfidentialInfo")
                        .HasColumnType("integer");

                    b.Property<int?>("NumOfISBackupProvided")
                        .HasColumnType("integer");

                    b.Property<int?>("NumOfServersSoftRedundancyMeasured")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Form2_13");
                });

            modelBuilder.Entity("CBSMonitoring.Models.Form2_14", b =>
                {
                    b.HasBaseType("CBSMonitoring.Models.OrgMonitoring");

                    b.Property<int?>("NumOfServersWithLicensedOS")
                        .HasColumnType("integer");

                    b.Property<int?>("NumOfServersWithUpdatingOs")
                        .HasColumnType("integer");

                    b.Property<int?>("NumOfWRoomswihLicensedOS")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Form2_14");
                });

            modelBuilder.Entity("CBSMonitoring.Models.Form2_15", b =>
                {
                    b.HasBaseType("CBSMonitoring.Models.OrgMonitoring");

                    b.Property<string>("FrequencyOfPrevMaintanence")
                        .HasColumnType("text");

                    b.Property<bool?>("IsPlannedPrevWorkAvailable")
                        .HasColumnType("boolean");

                    b.HasDiscriminator().HasValue("Form2_15");
                });

            modelBuilder.Entity("CBSMonitoring.Models.Form2_16", b =>
                {
                    b.HasBaseType("CBSMonitoring.Models.OrgMonitoring");

                    b.Property<bool?>("IsRecoveryPlansAvailable")
                        .HasColumnType("boolean");

                    b.HasDiscriminator().HasValue("Form2_16");
                });

            modelBuilder.Entity("CBSMonitoring.Models.Form2_17", b =>
                {
                    b.HasBaseType("CBSMonitoring.Models.OrgMonitoring");

                    b.Property<bool?>("AvailabilityOfFireAlarmSystInRoomWithSEq")
                        .HasColumnType("boolean");

                    b.Property<bool?>("AvailablityOfAlternativePowerL")
                        .HasColumnType("boolean");

                    b.Property<bool?>("AvailablityOfGenerators")
                        .HasColumnType("boolean");

                    b.Property<bool?>("AvailablityOfUPSForSEq")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsUPSAvailableForWRooms")
                        .HasColumnType("boolean");

                    b.Property<int?>("NumberOfGenerators")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfServersWithUPS")
                        .HasColumnType("integer");

                    b.Property<bool?>("PresenceOfGasFireExtSystInRoomWithSEq")
                        .HasColumnType("boolean");

                    b.Property<int?>("WorkRoomsWithUPS")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Form2_17");
                });

            modelBuilder.Entity("CBSMonitoring.Models.Form2_18", b =>
                {
                    b.HasBaseType("CBSMonitoring.Models.OrgMonitoring");

                    b.Property<bool?>("IsLogsOfCarriersOfConfInfAvailable")
                        .HasColumnType("boolean");

                    b.HasDiscriminator().HasValue("Form2_18");
                });

            modelBuilder.Entity("CBSMonitoring.Models.Form2_2", b =>
                {
                    b.HasBaseType("CBSMonitoring.Models.OrgMonitoring");

                    b.Property<DateTime?>("DeadlineOfPlan")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("DeadlineOfRealExec")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsExecuted")
                        .HasColumnType("boolean");

                    b.Property<int?>("SectNumber")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Form2_2");
                });

            modelBuilder.Entity("CBSMonitoring.Models.Form2_3", b =>
                {
                    b.HasBaseType("CBSMonitoring.Models.OrgMonitoring");

                    b.Property<bool?>("IsISystemAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsISystemResourcesAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsListOfProtectedObjAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsObjectsClasified")
                        .HasColumnType("boolean");

                    b.HasDiscriminator().HasValue("Form2_3");
                });

            modelBuilder.Entity("CBSMonitoring.Models.Form2_4", b =>
                {
                    b.HasBaseType("CBSMonitoring.Models.OrgMonitoring");

                    b.Property<DateTime?>("ContractDateOfOutsoucingOrg")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContractNumberOfOutsoucingOrg")
                        .HasColumnType("text");

                    b.Property<string>("EmailOfSectionHead")
                        .HasColumnType("text");

                    b.Property<string>("ISsecDivisionName")
                        .HasColumnType("text");

                    b.Property<bool?>("IsDevisionPositionPresent")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsISecDivisionPresent")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsOrganizationInvolvedInOutsourcingOfIS")
                        .HasColumnType("boolean");

                    b.Property<string>("ListOfServicesOfOutsourcingOrg")
                        .HasColumnType("text");

                    b.Property<string>("NameOfOutSourcingOrg")
                        .HasColumnType("text");

                    b.Property<int?>("NumberOfISEmployees")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumOfSectionHead")
                        .HasColumnType("text");

                    b.Property<string>("PositionOfSectionHead")
                        .HasColumnType("text");

                    b.Property<string>("SectionHeadFullName")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Form2_4");
                });

            modelBuilder.Entity("CBSMonitoring.Models.Form2_5", b =>
                {
                    b.HasBaseType("CBSMonitoring.Models.OrgMonitoring");

                    b.Property<string>("EmailOfRespPerson")
                        .HasColumnType("text");

                    b.Property<string>("FullNameOfRespPerSon")
                        .HasColumnType("text");

                    b.Property<bool?>("IsResponsiblePersonAssigned")
                        .HasColumnType("boolean");

                    b.Property<string>("PositionOfRespPerson")
                        .HasColumnType("text");

                    b.Property<string>("TelNumOfRespPerson")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Form2_5");
                });

            modelBuilder.Entity("CBSMonitoring.Models.Form2_6", b =>
                {
                    b.HasBaseType("CBSMonitoring.Models.OrgMonitoring");

                    b.Property<string>("EmailOfRespPersonForSecIssues")
                        .HasColumnType("text");

                    b.Property<string>("FullNameOfRespPersonForSecIssues")
                        .HasColumnType("text");

                    b.Property<bool?>("IsRespPersonAvailableForSecIssues")
                        .HasColumnType("boolean");

                    b.Property<string>("PositionOfRespPersonForSecIssues")
                        .HasColumnType("text");

                    b.Property<string>("TelNumberOfRespPersonForSecIssues")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Form2_6");
                });

            modelBuilder.Entity("CBSMonitoring.Models.Form2_7", b =>
                {
                    b.HasBaseType("CBSMonitoring.Models.OrgMonitoring");

                    b.Property<bool?>("IsInstructionPresent")
                        .HasColumnType("boolean");

                    b.Property<int?>("PositionInstructionCount")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Form2_7");
                });

            modelBuilder.Entity("CBSMonitoring.Models.Form2_8", b =>
                {
                    b.HasBaseType("CBSMonitoring.Models.OrgMonitoring");

                    b.Property<int?>("NumberOfEmpsQualificaitonImproved")
                        .HasColumnType("integer");

                    b.Property<int[]>("QualifImpEmpIds")
                        .HasColumnType("integer[]");

                    b.HasDiscriminator().HasValue("Form2_8");
                });

            modelBuilder.Entity("CBSMonitoring.Models.Form2_9", b =>
                {
                    b.HasBaseType("CBSMonitoring.Models.OrgMonitoring");

                    b.Property<DateTime?>("ExpertConclusionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExpertConclusionNumber")
                        .HasColumnType("text");

                    b.Property<string>("ExpertizingPeriod")
                        .HasColumnType("text");

                    b.Property<bool?>("HasShortcomings")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsShortcomingsOfWebsiteEliminated")
                        .HasColumnType("boolean");

                    b.Property<string>("WebAddress")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Form2_9");
                });

            modelBuilder.Entity("CBSMonitoring.Models.Form3_1", b =>
                {
                    b.HasBaseType("CBSMonitoring.Models.OrgMonitoring");

                    b.Property<string>("FrequencyOfPasswUpdateInWRooms")
                        .HasColumnType("text");

                    b.Property<string>("FrequncyOfPasswUpdateInSRooms")
                        .HasColumnType("text");

                    b.Property<bool?>("IsPasswProtectInSRooms")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsPasswProtectInWRooms")
                        .HasColumnType("boolean");

                    b.Property<int?>("NumberOfSRoomsWithPasswProtection")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfWRoomsWithPasswProtection")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Form3_1");
                });

            modelBuilder.Entity("CBSMonitoring.Models.Form3_10", b =>
                {
                    b.HasBaseType("CBSMonitoring.Models.OrgMonitoring");

                    b.Property<bool?>("IsLicenceOfDLPAvaliable")
                        .HasColumnType("boolean");

                    b.Property<string>("NameAndVersionOfDLP")
                        .HasColumnType("text");

                    b.Property<int?>("NumberOfWorkRoomsWithDLP")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Form3_10");
                });

            modelBuilder.Entity("CBSMonitoring.Models.Form3_11", b =>
                {
                    b.HasBaseType("CBSMonitoring.Models.OrgMonitoring");

                    b.Property<bool?>("IsLicenseForSIEMAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("NameAndVersionOfSIEM")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Form3_11");
                });

            modelBuilder.Entity("CBSMonitoring.Models.Form3_12", b =>
                {
                    b.HasBaseType("CBSMonitoring.Models.OrgMonitoring");

                    b.Property<string>("NameAndVersionOfCAndSAnalysisTool")
                        .HasColumnType("text");

                    b.Property<string>("NumberOfCAndSAnalysisTools")
                        .HasColumnType("text");

                    b.Property<string>("PurposeOfCAndSAnalysisTools")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Form3_12");
                });

            modelBuilder.Entity("CBSMonitoring.Models.Form3_13", b =>
                {
                    b.HasBaseType("CBSMonitoring.Models.OrgMonitoring");

                    b.Property<string>("NameOfProtectionTool")
                        .HasColumnType("text");

                    b.Property<int?>("NumberOfProtectionTool")
                        .HasColumnType("integer");

                    b.Property<string>("PurposeOfProtectionTool")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Form3_13");
                });

            modelBuilder.Entity("CBSMonitoring.Models.Form3_2", b =>
                {
                    b.HasBaseType("CBSMonitoring.Models.OrgMonitoring");

                    b.Property<bool?>("IsAccessControlToNetworkInCentreAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsAccessControlToNetworkInStrucDivAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("NameOfToolForAccessControlInCentre")
                        .HasColumnType("text");

                    b.Property<string>("NameOfToolsForAccessControl")
                        .HasColumnType("text");

                    b.Property<int?>("NumberOfOrgsWithAccesControlToNetwork")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Form3_2");
                });

            modelBuilder.Entity("CBSMonitoring.Models.Form3_3", b =>
                {
                    b.HasBaseType("CBSMonitoring.Models.OrgMonitoring");

                    b.Property<string>("FrequencyOfIDsChange")
                        .HasColumnType("text");

                    b.Property<bool?>("IsAccessControlSystemAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsAccessEventsAndLogsRecorded")
                        .HasColumnType("boolean");

                    b.Property<string>("NameOfACMTool")
                        .HasColumnType("text");

                    b.Property<int?>("NumberOfISWithACS")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfISWithConfInfUsingACS")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfISWithConfInfWithCryptKeys")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfISWithConfInfWithOnlyPassw")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfISWithCryptKeys")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfISWithOnlyPassw")
                        .HasColumnType("integer");

                    b.Property<string>("UserIDsInAccess")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Form3_3");
                });

            modelBuilder.Entity("CBSMonitoring.Models.Form3_4", b =>
                {
                    b.HasBaseType("CBSMonitoring.Models.OrgMonitoring");

                    b.Property<bool?>("IsLicenseForAntiMAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("NameAndVersionOfAntimalwareProgram")
                        .HasColumnType("text");

                    b.Property<int?>("NumberOfServersWithAntiM")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfWRoomsWithAntiM")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Form3_4");
                });

            modelBuilder.Entity("CBSMonitoring.Models.Form3_5", b =>
                {
                    b.HasBaseType("CBSMonitoring.Models.OrgMonitoring");

                    b.Property<bool?>("IsLicenceForFireWallAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("NameAndVersionOfFirewall")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Form3_5");
                });

            modelBuilder.Entity("CBSMonitoring.Models.Form3_6", b =>
                {
                    b.HasBaseType("CBSMonitoring.Models.OrgMonitoring");

                    b.Property<bool?>("IsLicenseForIDPSAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("NameAndVersionOfIDPS")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Form3_6");
                });

            modelBuilder.Entity("CBSMonitoring.Models.Form3_7", b =>
                {
                    b.HasBaseType("CBSMonitoring.Models.OrgMonitoring");

                    b.Property<bool?>("IsEXATAvailable")
                        .HasColumnType("boolean");

                    b.Property<int?>("NumberOfSystemsWithEXAT")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Form3_7");
                });

            modelBuilder.Entity("CBSMonitoring.Models.Form3_8", b =>
                {
                    b.HasBaseType("CBSMonitoring.Models.OrgMonitoring");

                    b.Property<bool?>("IsHUMOAvailable")
                        .HasColumnType("boolean");

                    b.Property<int?>("NumberOfsystemsWithHUMO")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Form3_8");
                });

            modelBuilder.Entity("CBSMonitoring.Models.Form3_9", b =>
                {
                    b.HasBaseType("CBSMonitoring.Models.OrgMonitoring");

                    b.Property<bool?>("IsVPNUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("PurposeAndScopeOfVPNConnections")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Form3_9");
                });

            modelBuilder.Entity("CBSMonitoring.Models.FileModel", b =>
                {
                    b.HasOne("CBSMonitoring.Models.Form1_1", null)
                        .WithMany("Files")
                        .HasForeignKey("Form1_1MonitoringId");

                    b.HasOne("CBSMonitoring.Models.Form2_1", null)
                        .WithMany("Files")
                        .HasForeignKey("Form2_1MonitoringId");

                    b.HasOne("CBSMonitoring.Models.Form2_2", null)
                        .WithMany("Files")
                        .HasForeignKey("Form2_2MonitoringId");

                    b.HasOne("CBSMonitoring.Models.Form2_3", null)
                        .WithMany("Files")
                        .HasForeignKey("Form2_3MonitoringId");

                    b.HasOne("CBSMonitoring.Models.Form2_4", null)
                        .WithMany("Files")
                        .HasForeignKey("Form2_4MonitoringId");
                });

            modelBuilder.Entity("CBSMonitoring.Models.FormItem", b =>
                {
                    b.HasOne("CBSMonitoring.Models.MonitoringForm", "MonitoringForm")
                        .WithMany("FormItems")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonitoringForm");
                });

            modelBuilder.Entity("CBSMonitoring.Models.OrgMonitoring", b =>
                {
                    b.HasOne("CBSMonitoring.Model.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("CBSMonitoring.Models.QualificationImprovedEmployee", b =>
                {
                    b.HasOne("CBSMonitoring.Models.FileModel", "Certificate")
                        .WithMany()
                        .HasForeignKey("CertificateFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CBSMonitoring.Models.Form2_8", null)
                        .WithMany("QualificationImprovedEmployees")
                        .HasForeignKey("Form2_8MonitoringId");

                    b.Navigation("Certificate");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CBSMonitoring.Models.MonitoringForm", b =>
                {
                    b.Navigation("FormItems");
                });

            modelBuilder.Entity("CBSMonitoring.Models.Form1_1", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("CBSMonitoring.Models.Form2_1", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("CBSMonitoring.Models.Form2_2", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("CBSMonitoring.Models.Form2_3", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("CBSMonitoring.Models.Form2_4", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("CBSMonitoring.Models.Form2_8", b =>
                {
                    b.Navigation("QualificationImprovedEmployees");
                });
#pragma warning restore 612, 618
        }
    }
}
